export const POINT_DRAW_PROBABILITY_PERCENT_DECIMAL_PLACES = 6;
export const POINT_DRAW_PROBABILITY_UNITS_PER_PERCENT =
	10 ** POINT_DRAW_PROBABILITY_PERCENT_DECIMAL_PLACES;
export const POINT_DRAW_TOTAL_PROBABILITY_UNITS =
	100 * POINT_DRAW_PROBABILITY_UNITS_PER_PERCENT;
