export const COMMUNITY_AUTHOR_NAME_MAX_LENGTH = 30;
export const COMMUNITY_BODY_JSON_MAX_LENGTH = 30_000;
export const COMMUNITY_COMMENT_BODY_MAX_LENGTH = 1000;
export const COMMUNITY_BODY_TEXT_MIN_LENGTH = 2;
export const COMMUNITY_PASSWORD_MIN_LENGTH = 4;
export const COMMUNITY_PASSWORD_MAX_LENGTH = 30;
export const COMMUNITY_TITLE_MIN_LENGTH = 2;
export const COMMUNITY_TITLE_MAX_LENGTH = 100;
