// 밤비 신뢰·안전 흐름 — 샘플 데이터

import { sampleCoverMedia } from "./sample-thumbnails";
import type {
	Job,
	ManagedUser,
	QueueItem,
	Report,
	ReportReason,
} from "./types";

const JOBS_SEED: Job[] = [
	// ── 스페셜(프리미엄) 노출 ──────────────────────────────────
	{
		id: "j2",
		title: "주말 야간 홀",
		company: "문스톤 라운지",
		location: "강남 · 논현",
		pay: "시급 17,000원",
		tags: ["주말", "고정", "장기 우대"],
		type: "라운지",
		hours: "19:00–01:00",
		pref: "장기 우대",
		featured: true,
		desc: "강남 논현 문스톤 라운지에서 주말 야간 근무자를 모십니다. 안정적으로 오래 일하실 분을 우대하고, 분위기 좋은 매장에서 함께할 동료를 찾아요.",
		status: "published",
		verified: true,
		rating: 4.8,
		reviews: 12,
		isPromoted: true,
		promotionTier: "premium",
		promotionLabel: "프리미엄",
		lastBoostedAt: "2026-07-01T18:00:00+09:00",
	},
	{
		id: "j6",
		title: "클럽 스태프",
		company: "네온 클럽",
		location: "강남 · 역삼",
		pay: "일급 150,000원",
		tags: ["주말", "고수익", "오늘 면접"],
		type: "클럽",
		hours: "21:00–05:00",
		pref: "체력 좋은 분",
		featured: false,
		desc: "강남 역삼 네온 클럽에서 주말 스태프를 모십니다. 활기찬 분위기에서 함께할 분을 찾아요. 일급으로 정산하며 당일 면접 가능합니다.",
		status: "published",
		verified: true,
		rating: 4.7,
		reviews: 21,
		isPromoted: true,
		promotionTier: "premium",
		promotionLabel: "프리미엄",
		lastBoostedAt: "2026-07-01T14:00:00+09:00",
	},
	{
		id: "j7",
		title: "홀 매니저",
		company: "청담 프라이빗 바운스",
		location: "강남 · 청담",
		pay: "월급 3,500,000원",
		tags: ["매니저", "경력", "정규직"],
		type: "라운지",
		hours: "20:00–04:00",
		pref: "홀 관리 경력",
		featured: false,
		desc: "청담 프라이빗 바운스에서 홀을 총괄할 매니저를 모십니다. 팀 관리와 고객 응대 경험이 있는 분을 우대하며, 처우는 면접 후 협의해요.",
		status: "published",
		verified: true,
		rating: 4.6,
		reviews: 7,
		isPromoted: true,
		promotionTier: "premium",
		promotionLabel: "프리미엄",
	},
	// ── 추천 노출 ─────────────────────────────────────────────
	{
		id: "j1",
		title: "홀 서빙",
		company: "달밤 라운지",
		location: "강남 · 청담",
		pay: "시급 18,000원",
		tags: ["주말", "야간", "초보 가능"],
		type: "라운지",
		hours: "20:00–02:00",
		pref: "주말 가능",
		featured: false,
		desc: "강남 청담 달밤 라운지에서 주말 야간 홀 서빙을 함께할 분을 찾습니다. 친절하고 성실한 분이면 누구나 환영해요. 첫 출근 전 충분히 안내해 드립니다.",
		status: "published",
		verified: true,
		rating: 4.9,
		reviews: 18,
		isPromoted: true,
		promotionTier: "recommended",
		lastBoostedAt: "2026-06-30T21:00:00+09:00",
	},
	{
		id: "j3",
		title: "바텐더",
		company: "시그니처 바",
		location: "강남 · 역삼",
		pay: "시급 16,000원",
		tags: ["경력 무관", "주 5일", "오늘 면접"],
		type: "바",
		hours: "21:00–03:00",
		pref: "칵테일 경험",
		featured: false,
		desc: "강남 역삼 시그니처 바에서 함께할 바텐더를 찾습니다. 경력 무관이며 기본기를 갖춘 분이면 좋아요. 레시피는 충분히 알려드립니다.",
		status: "published",
		verified: true,
		rating: 4.7,
		reviews: 9,
		isPromoted: true,
		promotionTier: "recommended",
		lastBoostedAt: "2026-06-30T12:00:00+09:00",
	},
	{
		id: "j8",
		title: "카페 홀",
		company: "무드 카페",
		location: "마포 · 홍대",
		pay: "시급 13,000원",
		tags: ["주간", "초보 가능", "장기 우대"],
		type: "카페",
		hours: "12:00–20:00",
		pref: "밝은 분",
		featured: true,
		desc: "마포 홍대 무드 카페에서 주간 홀 직원을 찾습니다. 초보도 친절히 알려드리고, 오래 함께할 분을 우대해요. 편안한 분위기입니다.",
		status: "published",
		verified: true,
		rating: 4.8,
		reviews: 15,
		isPromoted: true,
		promotionTier: "recommended",
	},
	// ── 전체(일반) 노출 ───────────────────────────────────────
	{
		id: "j4",
		title: "홀 서빙",
		company: "라운지 엘",
		location: "서초 · 교대",
		pay: "시급 15,000원",
		tags: ["초보 가능", "주 3일"],
		type: "라운지",
		hours: "19:00–01:00",
		pref: "성실한 분",
		featured: false,
		desc: "서초 교대 라운지 엘에서 홀 서빙 직원을 찾습니다. 초보도 환영하며 친절히 알려드려요. 주 3일부터 조율 가능합니다.",
		status: "published",
		verified: true,
		rating: 4.5,
		reviews: 6,
	},
	{
		id: "j9",
		title: "주말 홀",
		company: "루비 라운지",
		location: "송파 · 잠실",
		pay: "시급 16,000원",
		tags: ["주말", "야간"],
		type: "라운지",
		hours: "20:00–02:00",
		pref: "주말 가능",
		featured: false,
		desc: "송파 잠실 루비 라운지에서 주말 홀 직원을 찾습니다. 성실하게 함께할 분을 기다려요. 근무 조건은 면접에서 안내드립니다.",
		status: "published",
		verified: true,
		rating: 4.4,
		reviews: 5,
	},
	{
		id: "j10",
		title: "바 스태프",
		company: "하버 바",
		location: "인천 · 구월",
		pay: "시급 14,000원",
		tags: ["경력 무관", "오늘 면접"],
		type: "바",
		hours: "20:00–02:00",
		pref: "성실한 분",
		featured: false,
		desc: "인천 구월 하버 바에서 함께할 스태프를 찾습니다. 경력 무관이며 당일 면접도 가능해요. 편하게 문의 주세요.",
		status: "published",
		verified: false,
		rating: 4.3,
		reviews: 3,
	},
	{
		id: "j11",
		title: "주간 홀",
		company: "선셋 카페",
		location: "부천 · 상동",
		pay: "시급 12,500원",
		tags: ["주간", "초보 가능"],
		type: "카페",
		hours: "11:00–19:00",
		pref: "밝은 분",
		featured: false,
		desc: "부천 상동 선셋 카페에서 주간 홀 직원을 찾습니다. 초보도 환영하고 친절히 알려드려요. 주간 고정 근무입니다.",
		status: "published",
		verified: true,
		rating: 4.6,
		reviews: 8,
	},
	{
		id: "j12",
		title: "야간 홀",
		company: "미드나잇 라운지",
		location: "강남 · 신사",
		pay: "급여 협의",
		tags: ["야간", "고정"],
		type: "라운지",
		hours: "21:00–03:00",
		pref: "장기 우대",
		featured: false,
		desc: "강남 신사 미드나잇 라운지에서 야간 홀 직원을 찾습니다. 오래 함께할 분을 우대하며 처우는 면접 후 협의해요.",
		status: "published",
		verified: true,
		rating: 4.5,
		reviews: 4,
	},
];

// 각 공고에 샘플 썸네일을 랜덤(결정적)으로 배분한다. 실제 이미지 연동 전까지의 임시 처리.
export const JOBS: Job[] = JOBS_SEED.map((job) => ({
	...job,
	coverImage: sampleCoverMedia(job.id, `${job.company} 대표 이미지`),
}));

// 운영자 검수 큐 — 자동 필터에 걸려 사람 검수로 넘어온 공고
export const QUEUE: QueueItem[] = [
	{
		id: "q1",
		title: "홀 서빙 · 주말 야간",
		role: "홀 서빙 · 주말 야간",
		company: "달밤 라운지",
		location: "강남 · 청담",
		pay: "시급 18,000원",
		submitted: "2025.09.22 14:30",
		receivedAt: "2025.09.22 14:30",
		refId: "#48392",
		risk: "review",
		riskLevel: "high",
		detected: ["외모 우대", "20대만"],
		desc: "강남 청담 라운지에서 주말 야간 홀 서빙을 모집합니다. 밝고 활발한 20대만 지원 가능하며, 외모 우대합니다. 주말 고정으로 일하실 분을 환영해요.",
		flags: [
			{ label: "외모 차별 조건", sev: "review", match: "외모 우대" },
			{ label: "연령 차별 조건", sev: "review", match: "20대만" },
		],
	},
	{
		id: "q2",
		title: "바텐더",
		role: "바텐더",
		company: "문스톤 라운지",
		location: "강남 · 논현",
		pay: "시급 16,000원",
		submitted: "2025.09.22 13:10",
		receivedAt: "2025.09.22 13:10",
		refId: "#48391",
		risk: "review",
		riskLevel: "mid",
		detected: ["인센티브 500% 보장"],
		desc: "강남 논현 바텐더 모집. 기본급 외 인센티브 500% 보장으로 고수익이 가능합니다. 성실하게 오래 일하실 분을 찾습니다.",
		flags: [
			{ label: "과장 수익 표현", sev: "review", match: "인센티브 500% 보장" },
		],
	},
	{
		id: "q3",
		title: "홀 매니저",
		role: "홀 매니저",
		company: "시그니처 바",
		location: "강남 · 역삼",
		pay: "급여 협의",
		submitted: "2025.09.22 12:02",
		receivedAt: "2025.09.22 12:02",
		refId: "#48390",
		risk: "warn",
		riskLevel: "low",
		detected: ["경력 무관"],
		desc: "강남 역삼 시그니처 바 홀 매니저 모집. 경력 무관이며 친절히 교육해 드립니다. 책임감 있게 매장을 함께 운영할 분이면 좋아요.",
		flags: [{ label: "확인 필요 표현", sev: "warn", match: "경력 무관" }],
	},
	{
		id: "q4",
		title: "바텐더",
		role: "바텐더",
		company: "라운지 엘",
		location: "서초 · 교대",
		pay: "시급 17,000원",
		submitted: "2025.09.22 11:45",
		receivedAt: "2025.09.22 11:45",
		refId: "#48389",
		risk: "review",
		riskLevel: "mid",
		detected: ["단기 고수익 보장"],
		desc: "서초 교대 라운지 엘 바텐더 모집. 단기 고수익 보장으로 짧게 일해도 큰 수익을 가져갈 수 있어요. 편하게 문의 주세요.",
		flags: [
			{ label: "과장 수익 표현", sev: "review", match: "단기 고수익 보장" },
		],
	},
	{
		id: "q5",
		title: "홀 서빙",
		role: "홀 서빙",
		company: "청담 프라이빗",
		location: "강남 · 청담",
		pay: "시급 19,000원",
		submitted: "2025.09.22 11:20",
		receivedAt: "2025.09.22 11:20",
		refId: "#48388",
		risk: "review",
		riskLevel: "high",
		detected: ["지인 동반 필수"],
		desc: "청담 프라이빗 홀 서빙 모집. 지인 동반 필수이며, 함께 지원하면 더 좋은 조건으로 모십니다. 분위기 좋은 곳에서 일하실 분을 환영합니다.",
		flags: [
			{ label: "이상 채용 조건", sev: "review", match: "지인 동반 필수" },
		],
	},
];

// 운영자 조치를 기다리는 채팅 신고
export const REPORTS: Report[] = [
	{
		id: "r1",
		reason: "성매매·성적 서비스 암시",
		reporter: "김하늘",
		reporterRole: "구직자",
		target: "벨벳 나이트",
		targetRole: "구인자",
		time: "8분 전",
		sev: "high",
		status: "open",
		note: "면접 얘기 중에 다른 서비스를 계속 물어봐요.",
		thread: [
			{
				mine: false,
				text: "홀 서빙 지원하신 거 맞죠? 혹시 2차도 가능하신지 먼저 여쭤볼게요.",
			},
			{
				mine: true,
				text: "공고에는 홀 서빙이라고 되어 있었는데요. 그런 일은 생각 안 하고 있어요.",
			},
			{
				mine: false,
				text: "그럼 조건 맞춰서 따로 얘기해요. 카톡 아이디 주시면 자세히 설명할게요.",
			},
		],
	},
	{
		id: "r2",
		reason: "외부 연락처 유도",
		reporter: "박서준",
		reporterRole: "구직자",
		target: "하이드",
		targetRole: "구인자",
		time: "41분 전",
		sev: "mid",
		status: "open",
		note: "밤비 채팅 대신 계속 텔레그램으로 오라고 해요.",
		thread: [
			{
				mine: false,
				text: "여기 말고 텔레그램으로 연락 주세요. 아이디 알려드릴게요.",
			},
			{ mine: true, text: "면접 전에는 밤비 안에서 얘기하고 싶어요." },
		],
	},
	{
		id: "r3",
		reason: "허위 공고",
		reporter: "이도윤",
		reporterRole: "구직자",
		target: "오로라 클럽",
		targetRole: "구인자",
		time: "1시간 전",
		sev: "low",
		status: "open",
		note: "공고 급여와 실제로 말하는 금액이 너무 달라요.",
		thread: [
			{
				mine: false,
				text: "공고는 일급 13만원인데 실제로는 7만원부터 시작이에요.",
			},
			{ mine: true, text: "공고 내용이랑 너무 다른데요?" },
		],
	},
];

// 제재 화면용 사용자
export const USERS: ManagedUser[] = [
	{
		id: "u1",
		name: "벨벳 나이트",
		displayName: "벨벳 나이트",
		role: "구인자",
		joined: "2026.04",
		status: "active",
		reports: 3,
		warnings: 1,
		note: "성적 서비스 암시 신고 누적",
	},
	{
		id: "u2",
		name: "하이드",
		displayName: "하이드",
		role: "구인자",
		joined: "2026.05",
		status: "warned",
		reports: 1,
		warnings: 1,
		note: "외부 연락처 유도 1회 경고",
	},
	{
		id: "u3",
		name: "김민재",
		displayName: "김민재",
		role: "구직자",
		joined: "2026.03",
		status: "active",
		reports: 0,
		warnings: 0,
		note: "신고 이력 없음",
	},
];

export const REPORT_REASONS: ReportReason[] = [
	{ id: "sex", label: "성매매·성적 서비스 암시", sev: "high" },
	{ id: "coerce", label: "강요·협박·착취", sev: "high" },
	{ id: "minor", label: "미성년 관련", sev: "high" },
	{ id: "fake", label: "허위 공고·사기", sev: "mid" },
	{ id: "external", label: "외부 연락처 유도", sev: "mid" },
	{ id: "abuse", label: "욕설·혐오 표현", sev: "mid" },
	{ id: "etc", label: "기타", sev: "low" },
];
